version: "3.7"
services:
 kibana:
    image: kibana:6.4.2
    ports:
      - "5601:5601"
    networks:
      - mysql
      - nginx
  mysql:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    networks:
      - kibana
      - nginx
  nginx:
    build: nginx
    ports:
      - 80:80
    networks:
      - mysql
      - kibana
networks:
      - mysql
      - kibana
      - nginx
secrets:
  db-password:
    file: mysql/password.txt
